### ISSUE TITLE
Review/update all component macro options tables

### ISSUE THREAD

**Issue by jrbarnes9** [ONSdigital/design-system#2123]
To make it easier to rewrite the tests, ensure:
- all parameters used in macros are documented
- 'required' column of macro options is as expected
- invalid parameters removed from macro options

To do:
- [x] Access code
- [x] Accordion
- [x] Addresses (remove)
- [ ] Address input
- [x] Address output
- [x] Autosuggest
- [x] Breadcrumbs
- [x] Button
- [x] Call to action
- [x] Card
- [x] Character check limit
- [x] Checkboxes
- [x] Code highlight
- [x] Collapsible
- [x] Content pagination
- [x] Cookies banner
- [x] Date input
- [x] Document list
- [x] Duration
- [x] Error
- [x] External link
- [x] Feedback
- [x] Fieldset
- [x] Field
- [x] Footer
- [x] Header
- [x] Hero
- [ ] Icons
- [x] Images
- [x] Input
- [x] Label
- [x] Language selector
- [x] Lists
- [x] Message
- [x] Message list
- [x] Metadata
- [x] Modal
- [x] Mutually exclusive
- [x] Pagination
- [x] Panel
- [x] Password
- [x] Phase banner
- [x] Promotional banner
- [x] Question
- [x] Quote
- [x] Radios
- [x] Related content
- [x] Relationships
- [x] Reply
- [ ] Search
- [x] Section navigation
- [x] Select
- [x] Share page
- [x] Skip to content
- [x] Status
- [x] Summary
- [x] Table
- [x] Table of contents
- [x] Tabs
- [x] Text indent
- [x] Textarea
- [x] Timeline
- [x] Timeout modal
- [x] Timeout panel
- [x] Upload
- [x] Video
