### ISSUE TITLE
Use of colour: highlight contrast (WCAG 2.2 Level A - Accessibility)

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3031]
### Background
The eQ service identified this issue within the ONS Design System following their DAC audit report (18/01/2024).

### Issue
Colour was used as the sole means of identifying information or states.

![Image](https://github.com/ONSdigital/design-system/assets/102512949/37118381-c20e-4f0a-a863-c87f6d29cc2f)

The highlight applied to certain keywords within questions, such as ‘demonstration’ and ‘delivery mileage cars’ in the screenshot and below code reference does not contrast sufficiently with the white page background to meet WCAG AA. The yellow highlight colour could be difficult for some low vision users to see, meaning that these users may not understand the emphasis of this text in the same way as other users. 
In this case, the background colour is relied upon as the only means of indicating the importance of this text.
Highlight: #F0F762
Background: #FFFFFF
Contrast ratio: 1.2:1

**This issue applies throughout the service wherever this highlight colour has been used.**

### Suggested solution
Ensure that where colour is used to indicate information or importance, this colour change achieves a **contrast ratio of at least 3:1**. In this case, the highlight styling must achieve this contrast ratio against the white page background. The adjusted highlight colour should also retain a sufficient contrast ratio against the text, as per [1.4.3 Contrast (Minimum)](https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html). We also
recommend providing an additional visual indicator to aid users in identifying highlighted text, such as an outline.

### Tasks
- Investigate whether the change can be made and any impacts
- Decide the best solution
- Implement the solution
- Update eQ with progress

### Info
- [eQ DAC reports/docs](https://confluence.ons.gov.uk/display/SDC/eQ+DAC+Reports)
- Issue ID: DAC_Use_Of_Colour_01
- DAC report pages: 48 to 49
- WCAG Reference: 1.4.1 Use of Color (Level A):
  - [Understanding Use of Color](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html)
  - [How to Meet Use of Color](https://www.w3.org/WAI/WCAG22/quickref/#use-of-color)

**Comment by balibirchlee** [comment]
### Actions before developers can implement:

@Majsol @JNATION85 
- [ ] Agree colour for highlighting. 
- [ ] Agree on (not) implementing outline.

@daniellecorke 
- [ ]  Double check screenreader comments.


### Details

**Highlight Colour:**

This is easy enough to change, but there are decisions involved.

One thing to note is that it seems very difficult (might not be possible) to get a contrast level that will pass AAA standards for regular text, whilst maintaining 3:1 contrast between the highlight colour and the background white of the webpage. 

As the original highlight was from the 'supporting palette' - my recommendation would be to replace it with another colour from that pallette  `--ons-color-jaffa-orange: #fa6401;` this has the required contrast between the background and highlight and passes AA for regular text and AAA for large text. This change would affect all highlighting, including links that have been clicked on and highlights in tables.

**Outlining:**

As far as I'm aware it would be very difficult to outline the highlighting in the case that it is used for words in the middle of a body of text. In this case, we could also recommend underlining the text? I wouldn't advise adding an underline to all highlighting uses, because it has different uses across the Design System and for some the underline wouldn't be appropriate. 

**Screenreader Comments:**

This doesn't seem to be relevant to this ticket, as such I wanted to check if there's a relevant screenreader comment and that this comment is being addressed elsewhere?

**Comment by daniellecorke** [comment]
@balibirchlee  Apologies - my mistake. There are no screen reader comments for this issue. I've removed that part.

**Comment by rmccar** [comment]
Look into adding the underline in eQ and retest with DAC

**Comment by rmccar** [comment]
Change made in eQ
