### ISSUE TITLE
[Spike] Investigate dark mode option for the Service Manual

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3037]
### Background
We would like to investigate the feasibility of a dark mode version of the Service Manual.

### Tasks
- [ ]  Identify design options for dark mode (what would this look like)
- [ ]  Discuss ONS logo colours with brand guidelines
- [ ]  Team to decide whether to introduce dark mode as an option
- [ ]  If going ahead - raise further tickets to outline tech and design work
- [ ]  If going ahead - plan to reach out to community to gather feedback/thoughts

### Acceptance Criteria
- [ ]  Simple Figma prototype
- [ ]  Simple technical prototype
- [ ]  Team decision on whether to go ahead with implementation
- [ ]  Further tickets raised

**Comment by yatesn** [comment]
Add outcome

**Comment by daniellecorke** [comment]
This issue is currently parked on the UCD Board.
