### ISSUE TITLE
Investigate text colour for input into `accessiblePlaceholder`

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3043]
### Background/Issue

A Design System user reported the issue to us via the Slack channel and the Input discussions board #1383. 
When using the `accessiblePlaceholder` feature, the placeholder text is shown in the same colour black #222222 as actual entered text.
The user was expecting the placeholder text to be a lighter shade of grey i.e. #707071 as per standard ONS Input placeholder text. 

### Examples
**Top:** actual outcome 
**Bottom:** the outcome the user was expecting
![Image](https://github.com/ONSdigital/design-system/assets/102512949/a0f36bbf-f9f1-4dfa-bc7f-680b31000d9a)

### Tasks
- [ ] Investigate the issue and identify a potential fix in relation to the colour
- [ ] Discuss within team to decide the appropriate action to take
- [ ] Raise further tickets if needed
