### ISSUE TITLE
Investigate dates pattern feedback

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3098]
### Background
A user provided feedback on the [dates pattern](https://service-manual.ons.gov.uk/design-system/patterns/dates) via the Discussions board #22. 

### Issue

User feedback provided:
> This component contains invalid html and is therefore breaking web standards. The min and max [attributes are not valid](https://html.spec.whatwg.org/multipage/input.html#the-min-and-max-attributes) on input type of text and considering that browser validation is recommended to be [turned off](https://service-manual.ons.gov.uk/design-system/patterns/correct-errors#turn-off-html5-validation) there's little value in having them. [Self closing tags](https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags) are also invalid /> and should be removed.

### Tasks
- [x] Investigate the issue and research the relevant standards
- [x] Decide whether changes need to be made to the pattern
- [x] If so, raise a ticket outlining the work required
- [x] PM to update the user

### Definition of Done
- [x] We know whether we will makes changes to this pattern
- [x] A ticket(s) is raised to cover the work required
- [x] The user has been updated

**Comment by rmccar** [comment]
On inputs that have the `type` param set to "number" we override that with "text" due to a bug with Firefox and Safari (https://bugzilla.mozilla.org/show_bug.cgi?id=1398528). So we should remove the `min` and `max` attributes for inputs that have this type.

For the self closing tags, this is not invalid HTML so we don't need to make that change.

**Comment by daniellecorke** [comment]
I have updated the user with the outcome of this ticket.
