### ISSUE TITLE
[Spike] Investigate if we can introduce a loading component

### ISSUE THREAD

**Issue by daniellecorke** [ONSdigital/design-system#3110]
### Background

We don't currently have a loading component in the Design System. 

There is a loader variants under 'Buttons' however would not be suitable for all uses. For example, when using the [Upcoming Pages](https://service-manual.ons.gov.uk/community/what-were-working-on/upcoming-changes)  on the Service Manual, the information takes a while to load but there is nothing displayed to let the user know. 

### Tasks
- [ ] Investigate the feasibility of a loading component and what this would look like. 
- [ ] Decide whether to introduce this to the Design System. 
- [ ] If required, further tickets written for the work needed to implement this. 

### Acceptance Criteria
We know if we will implement a loading component. If we decide to implement this, tickets are written to outline the required work.

**Comment by daniellecorke** [comment]
On the UCD Board: https://jira.ons.gov.uk/browse/CU-93.

**Comment by daniellecorke** [comment]
This issue is currently parked on the UCD Board.

**Comment by e-livingstone** [comment]
Blocked; this has been parked on the UCD board.

**Comment by Olatunde-Alalade-ONS** [comment]
Track further updates at [CU-93](https://officefornationalstatistics.atlassian.net/browse/CU-93)

[CU-93]: https://officefornationalstatistics.atlassian.net/browse/CU-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
